apiVersion: v1
kind: Pod
metadata:
  labels:
    app: custom-nginx-application
  name: custom-nginx-application
spec:
  containers:
  - image: rajesh17mca/my-custom-nginx:latest
    name: custom-nginx-application
    
    resources: 
      requests:
        cpu: "1"
        memory: "500M"
      limits:
        cpu: "1"
        memory: "500M"
    ports:
    - containerPort: 80
      name: app-port
      protocol: TCP
  dnsPolicy: ClusterFirst
  restartPolicy: Always
