apiVersion: v1
kind: Service
metadata:
  name: custom-nginx-application-service
spec:
  selector:
    app: custom-nginx-application # This must match the label in your Deployment YAML
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
